# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ralvarezdev/certificate.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ralvarezdev/certificate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dralvarezdev/certificate.proto\x12\x0bralvarezdev\"\xaa\x01\n\x1aGenerateCertificateRequest\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x14\n\x0corganization\x18\x02 \x01(\t\x12\x1b\n\x13organizational_unit\x18\x03 \x01(\t\x12\x10\n\x08locality\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x12\n\npublic_key\x18\x07 \x01(\x0c\".\n\x1bGenerateCertificateResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"1\n\x1aValidateCertificateRequest\x12\x13\n\x0b\x63\x65rtificate\x18\x01 \x01(\x0c\"/\n\x1bValidateCertificateResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\"*\n\x13GetPublicKeyRequest\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\"*\n\x14GetPublicKeyResponse\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x32\xba\x02\n\x0b\x43\x65rtificate\x12j\n\x13GenerateCertificate\x12\'.ralvarezdev.GenerateCertificateRequest\x1a(.ralvarezdev.GenerateCertificateResponse0\x01\x12j\n\x13ValidateCertificate\x12\'.ralvarezdev.ValidateCertificateRequest\x1a(.ralvarezdev.ValidateCertificateResponse(\x01\x12S\n\x0cGetPublicKey\x12 .ralvarezdev.GetPublicKeyRequest\x1a!.ralvarezdev.GetPublicKeyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ralvarezdev.certificate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATECERTIFICATEREQUEST']._serialized_start=47
  _globals['_GENERATECERTIFICATEREQUEST']._serialized_end=217
  _globals['_GENERATECERTIFICATERESPONSE']._serialized_start=219
  _globals['_GENERATECERTIFICATERESPONSE']._serialized_end=265
  _globals['_VALIDATECERTIFICATEREQUEST']._serialized_start=267
  _globals['_VALIDATECERTIFICATEREQUEST']._serialized_end=316
  _globals['_VALIDATECERTIFICATERESPONSE']._serialized_start=318
  _globals['_VALIDATECERTIFICATERESPONSE']._serialized_end=365
  _globals['_GETPUBLICKEYREQUEST']._serialized_start=367
  _globals['_GETPUBLICKEYREQUEST']._serialized_end=409
  _globals['_GETPUBLICKEYRESPONSE']._serialized_start=411
  _globals['_GETPUBLICKEYRESPONSE']._serialized_end=453
  _globals['_CERTIFICATE']._serialized_start=456
  _globals['_CERTIFICATE']._serialized_end=770
# @@protoc_insertion_point(module_scope)
