# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ralvarezdev import certificate_pb2 as ralvarezdev_dot_certificate__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ralvarezdev/certificate_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CertificateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCertificate = channel.unary_stream(
                '/ralvarezdev.Certificate/GenerateCertificate',
                request_serializer=ralvarezdev_dot_certificate__pb2.GenerateCertificateRequest.SerializeToString,
                response_deserializer=ralvarezdev_dot_certificate__pb2.GenerateCertificateResponse.FromString,
                _registered_method=True)
        self.ValidateCertificate = channel.stream_unary(
                '/ralvarezdev.Certificate/ValidateCertificate',
                request_serializer=ralvarezdev_dot_certificate__pb2.ValidateCertificateRequest.SerializeToString,
                response_deserializer=ralvarezdev_dot_certificate__pb2.ValidateCertificateResponse.FromString,
                _registered_method=True)
        self.GetPublicKey = channel.unary_unary(
                '/ralvarezdev.Certificate/GetPublicKey',
                request_serializer=ralvarezdev_dot_certificate__pb2.GetPublicKeyRequest.SerializeToString,
                response_deserializer=ralvarezdev_dot_certificate__pb2.GetPublicKeyResponse.FromString,
                _registered_method=True)


class CertificateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateCertificate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPublicKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CertificateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCertificate': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateCertificate,
                    request_deserializer=ralvarezdev_dot_certificate__pb2.GenerateCertificateRequest.FromString,
                    response_serializer=ralvarezdev_dot_certificate__pb2.GenerateCertificateResponse.SerializeToString,
            ),
            'ValidateCertificate': grpc.stream_unary_rpc_method_handler(
                    servicer.ValidateCertificate,
                    request_deserializer=ralvarezdev_dot_certificate__pb2.ValidateCertificateRequest.FromString,
                    response_serializer=ralvarezdev_dot_certificate__pb2.ValidateCertificateResponse.SerializeToString,
            ),
            'GetPublicKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPublicKey,
                    request_deserializer=ralvarezdev_dot_certificate__pb2.GetPublicKeyRequest.FromString,
                    response_serializer=ralvarezdev_dot_certificate__pb2.GetPublicKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ralvarezdev.Certificate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ralvarezdev.Certificate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Certificate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ralvarezdev.Certificate/GenerateCertificate',
            ralvarezdev_dot_certificate__pb2.GenerateCertificateRequest.SerializeToString,
            ralvarezdev_dot_certificate__pb2.GenerateCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateCertificate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ralvarezdev.Certificate/ValidateCertificate',
            ralvarezdev_dot_certificate__pb2.ValidateCertificateRequest.SerializeToString,
            ralvarezdev_dot_certificate__pb2.ValidateCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPublicKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ralvarezdev.Certificate/GetPublicKey',
            ralvarezdev_dot_certificate__pb2.GetPublicKeyRequest.SerializeToString,
            ralvarezdev_dot_certificate__pb2.GetPublicKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
