# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ralvarezdev import decrypter_pb2 as ralvarezdev_dot_decrypter__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ralvarezdev/decrypter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecrypterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveEncryptedFile = channel.stream_unary(
                '/ralvarezdev.Decrypter/ReceiveEncryptedFile',
                request_serializer=ralvarezdev_dot_decrypter__pb2.ReceiveEncryptFileRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveEncryptedFile = channel.unary_unary(
                '/ralvarezdev.Decrypter/RemoveEncryptedFile',
                request_serializer=ralvarezdev_dot_decrypter__pb2.RemoveEncryptedFileRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveEncryptedFiles = channel.unary_unary(
                '/ralvarezdev.Decrypter/RemoveEncryptedFiles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListActiveFiles = channel.unary_unary(
                '/ralvarezdev.Decrypter/ListActiveFiles',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=ralvarezdev_dot_decrypter__pb2.ListActiveFilesResponse.FromString,
                _registered_method=True)
        self.DecryptFile = channel.unary_stream(
                '/ralvarezdev.Decrypter/DecryptFile',
                request_serializer=ralvarezdev_dot_decrypter__pb2.DecryptFileRequest.SerializeToString,
                response_deserializer=ralvarezdev_dot_decrypter__pb2.DecryptFileResponse.FromString,
                _registered_method=True)


class DecrypterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveEncryptedFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveEncryptedFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveEncryptedFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListActiveFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecryptFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecrypterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveEncryptedFile': grpc.stream_unary_rpc_method_handler(
                    servicer.ReceiveEncryptedFile,
                    request_deserializer=ralvarezdev_dot_decrypter__pb2.ReceiveEncryptFileRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveEncryptedFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveEncryptedFile,
                    request_deserializer=ralvarezdev_dot_decrypter__pb2.RemoveEncryptedFileRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveEncryptedFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveEncryptedFiles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListActiveFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListActiveFiles,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=ralvarezdev_dot_decrypter__pb2.ListActiveFilesResponse.SerializeToString,
            ),
            'DecryptFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DecryptFile,
                    request_deserializer=ralvarezdev_dot_decrypter__pb2.DecryptFileRequest.FromString,
                    response_serializer=ralvarezdev_dot_decrypter__pb2.DecryptFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ralvarezdev.Decrypter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ralvarezdev.Decrypter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Decrypter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveEncryptedFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ralvarezdev.Decrypter/ReceiveEncryptedFile',
            ralvarezdev_dot_decrypter__pb2.ReceiveEncryptFileRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveEncryptedFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ralvarezdev.Decrypter/RemoveEncryptedFile',
            ralvarezdev_dot_decrypter__pb2.RemoveEncryptedFileRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveEncryptedFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ralvarezdev.Decrypter/RemoveEncryptedFiles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListActiveFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ralvarezdev.Decrypter/ListActiveFiles',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ralvarezdev_dot_decrypter__pb2.ListActiveFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecryptFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ralvarezdev.Decrypter/DecryptFile',
            ralvarezdev_dot_decrypter__pb2.DecryptFileRequest.SerializeToString,
            ralvarezdev_dot_decrypter__pb2.DecryptFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
