# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ralvarezdev/decrypter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ralvarezdev/decrypter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bralvarezdev/decrypter.proto\x12\x0bralvarezdev\x1a\x1bgoogle/protobuf/empty.proto\"p\n\x16SendEncryptFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63ontent_hash\x18\x03 \x01(\x0c\x12\x1d\n\x15\x65ncrypted_aes_256_key\x18\x04 \x01(\x0c\"7\n\x0c\x43ompanyFiles\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\x12\x11\n\tfilenames\x18\x02 \x03(\t\"L\n\x18ListCompanyFilesResponse\x12\x30\n\rcompany_files\x18\x01 \x03(\x0b\x32\x19.ralvarezdev.CompanyFiles\"&\n\x12\x44\x65\x63ryptFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\xa5\x01\n\x13\x44\x65\x63ryptFileResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63ommon_name\x18\x02 \x01(\t\x12\x14\n\x0corganization\x18\x03 \x01(\t\x12\x1b\n\x13organizational_unit\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\r\n\x05state\x18\x06 \x01(\t\x12\x10\n\x08locality\x18\x07 \x01(\t2\x86\x02\n\tDecrypter\x12R\n\x11SendEncryptedFile\x12#.ralvarezdev.SendEncryptFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12Q\n\x10ListCompanyFiles\x12\x16.google.protobuf.Empty\x1a%.ralvarezdev.ListCompanyFilesResponse\x12R\n\x0b\x44\x65\x63ryptFile\x12\x1f.ralvarezdev.DecryptFileRequest\x1a .ralvarezdev.DecryptFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ralvarezdev.decrypter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDENCRYPTFILEREQUEST']._serialized_start=73
  _globals['_SENDENCRYPTFILEREQUEST']._serialized_end=185
  _globals['_COMPANYFILES']._serialized_start=187
  _globals['_COMPANYFILES']._serialized_end=242
  _globals['_LISTCOMPANYFILESRESPONSE']._serialized_start=244
  _globals['_LISTCOMPANYFILESRESPONSE']._serialized_end=320
  _globals['_DECRYPTFILEREQUEST']._serialized_start=322
  _globals['_DECRYPTFILEREQUEST']._serialized_end=360
  _globals['_DECRYPTFILERESPONSE']._serialized_start=363
  _globals['_DECRYPTFILERESPONSE']._serialized_end=528
  _globals['_DECRYPTER']._serialized_start=531
  _globals['_DECRYPTER']._serialized_end=793
# @@protoc_insertion_point(module_scope)
