# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ralvarezdev/decrypter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ralvarezdev/decrypter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bralvarezdev/decrypter.proto\x12\x0bralvarezdev\x1a\x1bgoogle/protobuf/empty.proto\"c\n\x19ReceiveEncryptFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x19\n\x11\x65ncrypted_content\x18\x02 \x01(\x0c\x12\x19\n\x11\x63ontent_signature\x18\x03 \x01(\x0c\"C\n\x1aRemoveEncryptedFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommon_name\x18\x02 \x01(\t\"6\n\x0c\x43ompanyFiles\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x11\n\tfilenames\x18\x02 \x03(\t\"K\n\x17ListActiveFilesResponse\x12\x30\n\rcompany_files\x18\x01 \x03(\x0b\x32\x19.ralvarezdev.CompanyFiles\"&\n\x12\x44\x65\x63ryptFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"+\n\x13\x44\x65\x63ryptFileResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x32\xaa\x03\n\tDecrypter\x12X\n\x14ReceiveEncryptedFile\x12&.ralvarezdev.ReceiveEncryptFileRequest\x1a\x16.google.protobuf.Empty(\x01\x12V\n\x13RemoveEncryptedFile\x12\'.ralvarezdev.RemoveEncryptedFileRequest\x1a\x16.google.protobuf.Empty\x12\x46\n\x14RemoveEncryptedFiles\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12O\n\x0fListActiveFiles\x12\x16.google.protobuf.Empty\x1a$.ralvarezdev.ListActiveFilesResponse\x12R\n\x0b\x44\x65\x63ryptFile\x12\x1f.ralvarezdev.DecryptFileRequest\x1a .ralvarezdev.DecryptFileResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ralvarezdev.decrypter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVEENCRYPTFILEREQUEST']._serialized_start=73
  _globals['_RECEIVEENCRYPTFILEREQUEST']._serialized_end=172
  _globals['_REMOVEENCRYPTEDFILEREQUEST']._serialized_start=174
  _globals['_REMOVEENCRYPTEDFILEREQUEST']._serialized_end=241
  _globals['_COMPANYFILES']._serialized_start=243
  _globals['_COMPANYFILES']._serialized_end=297
  _globals['_LISTACTIVEFILESRESPONSE']._serialized_start=299
  _globals['_LISTACTIVEFILESRESPONSE']._serialized_end=374
  _globals['_DECRYPTFILEREQUEST']._serialized_start=376
  _globals['_DECRYPTFILEREQUEST']._serialized_end=414
  _globals['_DECRYPTFILERESPONSE']._serialized_start=416
  _globals['_DECRYPTFILERESPONSE']._serialized_end=459
  _globals['_DECRYPTER']._serialized_start=462
  _globals['_DECRYPTER']._serialized_end=888
# @@protoc_insertion_point(module_scope)
