# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ralvarezdev import encrypter_pb2 as ralvarezdev_dot_encrypter__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ralvarezdev/encrypter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EncrypterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EncryptFile = channel.stream_unary(
                '/ralvarezdev.Encrypter/EncryptFile',
                request_serializer=ralvarezdev_dot_encrypter__pb2.EncryptFileRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GenerateCertificate = channel.unary_stream(
                '/ralvarezdev.Encrypter/GenerateCertificate',
                request_serializer=ralvarezdev_dot_encrypter__pb2.GenerateCertificateRequest.SerializeToString,
                response_deserializer=ralvarezdev_dot_encrypter__pb2.GenerateCertificateResponse.FromString,
                _registered_method=True)


class EncrypterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EncryptFile(self, request_iterator, context):
        """Upload a file using streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCertificate(self, request, context):
        """Generate certificate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncrypterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EncryptFile': grpc.stream_unary_rpc_method_handler(
                    servicer.EncryptFile,
                    request_deserializer=ralvarezdev_dot_encrypter__pb2.EncryptFileRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GenerateCertificate': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateCertificate,
                    request_deserializer=ralvarezdev_dot_encrypter__pb2.GenerateCertificateRequest.FromString,
                    response_serializer=ralvarezdev_dot_encrypter__pb2.GenerateCertificateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ralvarezdev.Encrypter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ralvarezdev.Encrypter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Encrypter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EncryptFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ralvarezdev.Encrypter/EncryptFile',
            ralvarezdev_dot_encrypter__pb2.EncryptFileRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ralvarezdev.Encrypter/GenerateCertificate',
            ralvarezdev_dot_encrypter__pb2.GenerateCertificateRequest.SerializeToString,
            ralvarezdev_dot_encrypter__pb2.GenerateCertificateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
