# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ralvarezdev/encrypter.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ralvarezdev/encrypter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bralvarezdev/encrypter.proto\x12\x0bralvarezdev\"7\n\x12\x45ncryptFileRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\"O\n\x13\x45ncryptFileResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x03 \x01(\x03\"\x94\x01\n\x1aGenerateCertificateRequest\x12\x13\n\x0b\x63ommon_name\x18\x01 \x01(\t\x12\x14\n\x0corganization\x18\x02 \x01(\t\x12\x19\n\x11organization_unit\x18\x03 \x01(\t\x12\x10\n\x08locality\x18\x04 \x01(\t\x12\r\n\x05state\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\".\n\x1bGenerateCertificateResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xcb\x01\n\tEncrypter\x12R\n\x0b\x45ncryptFile\x12\x1f.ralvarezdev.EncryptFileRequest\x1a .ralvarezdev.EncryptFileResponse(\x01\x12j\n\x13GenerateCertificate\x12\'.ralvarezdev.GenerateCertificateRequest\x1a(.ralvarezdev.GenerateCertificateResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ralvarezdev.encrypter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTFILEREQUEST']._serialized_start=44
  _globals['_ENCRYPTFILEREQUEST']._serialized_end=99
  _globals['_ENCRYPTFILERESPONSE']._serialized_start=101
  _globals['_ENCRYPTFILERESPONSE']._serialized_end=180
  _globals['_GENERATECERTIFICATEREQUEST']._serialized_start=183
  _globals['_GENERATECERTIFICATEREQUEST']._serialized_end=331
  _globals['_GENERATECERTIFICATERESPONSE']._serialized_start=333
  _globals['_GENERATECERTIFICATERESPONSE']._serialized_end=379
  _globals['_ENCRYPTER']._serialized_start=382
  _globals['_ENCRYPTER']._serialized_end=585
# @@protoc_insertion_point(module_scope)
